version: "2.1"
services:
  mongo:
    image: mongo:3.2.4
    ports:
    - 27017:27017
    command: --smallfiles

  spring-boot-mongo-docker:
    build: ./
    ports:
    - 8080:8080
    - 5005:5005
    links:
    - mongo
    entrypoint: "java $JAVA_OPTS -jar /app.jar"


